### ISSUE TITLE
Could the code train now without convergence ?

### ISSUE THREAD

**Issue by landian60** [JiauZhang/GigaGAN#2]
I found adding the cross attention module would make the training become unstable. The G loss raised to NaN.

**Comment by JiauZhang** [comment]
Now I'm trying unconditional generation with self-attention.

**Comment by landian60** [comment]
或许我们可以加个联系方式讨论一下？

**Comment by JiauZhang** [comment]
不好意思，假期没看git，有啥好的想法直接在issue里讨论吧，这样大家都可以看到😃
