### ISSUE TITLE
How can I contribute to your work

### ISSUE THREAD

**Issue by ofirkris** [JiauZhang/GigaGAN#3]
Hello, great effort on this re-implementation.
Would you need GPU resources / other assistance to complete your work? How far are you from achieving the paper results for the upscaler?

**Comment by JiauZhang** [comment]
I am currently conducting experiments on a small dataset `lambdalabs/pokemon-blip-captions`, so there are not too strict requirements for computing resources. However, having more computing resources can accelerate the experimental process.
